### ISSUE TITLE
Potential new unused blockstates in 1.19.3+exp

### ISSUE THREAD

**Issue by FavoritoHJS** [TheEpicBlock/PolyMc#205]
Do note that this is from a quick reading, there are probably multiple reasons why these can't be added.

- [ ] Head-tuned Note Blocks
  - This is due to mob heads getting their own instrument sounds, and thus blockstates, which can probably be reused.
- [ ] Hanging Signs
  - If not all blockstates are obtainable (thinking about Hanging, Straight Chains but not Axis Aligned) that could be some extra blockstates
    - Might be laggy due to attempted text rendering? Research needed.
- [ ] Bamboo stuff
  - Bamboo Double Slabs, Waterlogged Double Slabs, Signs, Buttons, Fence Gates, Doors, Trapdoors... Make sure these are all accounted for and can be used.

...that was less than i expected. Still worth keeping in mind.

PS: Custom fires might be possible by using the age tag. Probably useless though.

**Comment by TheEpicBlock** [comment]
Noteblocks should already work. I don't believe signs have any states. The other 1.20 stuff is waiting until I have a nice way to make use of all of them when the feature flag is deactivated. Custom fires are in fact possible and I should probably add a case for that, I'll add it to the general block list. (Note that fire is useless for anything other than fire, because it'll ignite the player clientside)
