### ISSUE TITLE
Use CustomModelData blocks once block limit has been reached

### ISSUE THREAD

**Issue by MrCubicYT** [TheEpicBlock/PolyMc#208]
Just an idea I had, would it be possible for when all the blockstates are used up for the mod to fallback to using Item Frames with Custom Model Data for blocks so in theory you can get rid of the block limit. You could also add an option to the config to toggle this for people who don't like the look of the CustomModelData blocks...

**Comment by TheEpicBlock** [comment]
No, this is way too dangerous. You can't have too many of those kinds of blocks because you'll start lagging the client quite quickly. It's only really fit for furniture mods where you're likely to only have a couple of those blocks, it's not suited for building blocks. Especially with worldgen mods this will become an instant client deathray.

That said, I should probably add this as an option to PolyConfig! This will give enough flexibility so you can easily make any amount of blocks be rendered with entities.

**Comment by TheEpicBlock** [comment]
I've created an issue on PolyConfig to keep track of this: https://github.com/TheEpicBlock/PolyConfig/issues/3

**Comment by skerit** [comment]
I made a custom BlockPoly that does this, still using ItemFrames though:
https://github.com/skerit/polymc-plus/blob/1.19/src/main/java/rocks/blackblock/polymcplus/block/ItemBlockPoly.java

I'm using it precisely for what you suggested: furniture. And some other mods that don't generate naturally, or are available in survival.
