### ISSUE TITLE
Recipe Book Issues

### ISSUE THREAD

**Issue by IAmSneak** [TheEpicBlock/PolyMc#40]
Java version 8
Version 2.3.0 for 1.16.2

1) Recipes requiring sticks are shown as craftable when there are modded items in your inventory and the other ingredients. 
2) Some custom recipes do not show up. Example being a 2x compressed cobblestone requiring 9, 1x compressed cobblestone.

**Comment by TheEpicBlock** [comment]
1; I don't know if we can fix this. Except for using more different items. But usually mods add quite a load of items and the change of items overlapping is quite large. So it will only be a mitigation.

2; sounds weird. Are you sure you have the recipe unlocked in the recipe book? I know Minecraft is sometimes a bit funky if it gives the recipe or not.

**Comment by IAmSneak** [comment]
The recipe is definitely unlocked and if I search it in the recipe book and filter by uncraftable, it shows it as craftable. Is it required to have the item being a stick? If it isn't then a different item could be used, potentially one used in less recipes. Potential items could be a debug stick or an empty firework star.

**Comment by TheEpicBlock** [comment]
We could definitely start using different ttems for things. The thing is, this issue also affects modded items. Say a mod adds 2 ingots and 2 pickaxe recipes for each one. If both ingots are polyd to a stick, the recipe will mess up and show both pickaxes as available, even if you only have one type of ingot. The only fix for this is to poly the ingots to different items. I'll see if I can think of a few different ones that don't have special properties, like the debug stick having an enchantment glint, and if I can make the system distribute the items evenly over them

**Comment by IAmSneak** [comment]
What if you had something like [NBT Crafting](https://www.curseforge.com/minecraft/mc-mods/nbt-crafting) and modified the recipes of all items. Not sure how easy this would be and this would probably be low priority, but considering how much this mod has done so far I don't think it would be outside the realm of possibility. This might cause issues of its own, such as being unable to craft with renamed items but it would clean up the recipe book a lot.

**Comment by TheEpicBlock** [comment]
PolyMc already edits the recipes to use sticks instead of the modded item. It also adds the CustomModelData to that stick. But from this issue I figure Minecraft doesn't check the cmd when determining if the recipe is craftable. I don't think NBT Crafting can make the client care about this fact either. In fact, it looks like NBT Crafting [blocks](https://github.com/Siphalor/nbt-crafting/blob/1.15-2.0/src/main/java/de/siphalor/nbtcrafting/mixin/network/MixinSynchronizeRecipesS2CPacket.java) all of the custom recipes from appearing in the recipe book if the client mod isn't installed. Something which I would rather not do, as the recipe book is quite helpful with most mods.

**Comment by TheEpicBlock** [comment]
I'll fix this by trying to use more unusual items. Things like glistering watermelons. And by trying to spread the load out over multiple items, instead of just using one (to mitigate conflict between modded items). Don't know when I'll have the time though :+1:
