### ISSUE TITLE
Placing a Block Beneath a Modded Block Changes the Modded Blocks Texture

### ISSUE THREAD

**Issue by IAmSneak** [TheEpicBlock/PolyMc#42]
[Example](https://streamable.com/9wkyre)

**Comment by MaryWeeb** [comment]
Suggestion: Replace noteblocks with spawners spawning armor stands holding custom model items

**Comment by TheEpicBlock** [comment]
The big advantage of noteblocks is that they're rendered as blocks, and are culled properly. This means there is no difference in fps between the actual modded block and a noteblock replica. Now I admit that I haven't tested how spawners perform, but I can't imagine it doing well, especially if the block is common. I was thinking of 2 other solutions.

Using mushroom blocks instead of noteblocks 
This has the benefit of also not having a right-click action. (which is quite annoying if you're in a custom biome and trying to hold up a shield, but the only thing you're doing is right-clicking the ground 😅). Downside is that it would remove a vanilla mechanic, you would never be able to see if sides are shaven off. That's why I will probably hide this under a config.

Second option is to do some cursed as hell update stuff. The problem here is that the client recalculates the noteblock and which instrument it should be. Don't know why its necessary to predict that on the client but apparently it is. We could send an update to the client with the real block. The downside is that this will probably require some real mixin hacks.
